[mc.round_schedule]
enabled = true
timezone = "Russian Standard Time"
update_frequency = 60
days = "Saturday,Sunday"
start = "17:00"
end = "24:00"

[accessibility]
screen_shake_intensity = 1

[admin]
deadmin_on_join = false
see_own_notes = true
server_ban_erase_player = true
new_player_threshold = 600
alert.explosion_min_intensity = -1

[adminlogs]
server_name = "TTMC"

[atmos]
space_wind = false
monstermos_rip_tiles = false
grid_impulse = false
max_process_time = 1

[auth]
mode = 1

[events]
enabled = false

[explosion]
can_create_vacuum = false

[game]
hostname = "[RU][LRP] üå™Ô∏è TornadoTech's Marine Corps ‚Äî Main"
desc = "–°–±–æ—Ä–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞ –æ—Å–Ω–æ–≤–∞–Ω–∞ –Ω–∞ https://github.com/ttmc14/ttmc14"
defaultpreset = "MCDistressSignal"
fallbackenabled = false
fallbackpreset = "MCDistressSignal"
round_end_sound_collection = "CMRoundEnd"
map = "MCPillarOfSpring"
contraband_examine = false
maxplayers = 100
soft_max_players = 60
panic_bunker.enabled = false
round_end_pvs_overrides = false
round_restart_time = 180
lobbyduration = 180

[movement]
mob_pushing = true

[ooc]
enable_during_round = true

[gateway]
generator_enabled = false

[ghost]
kill_crit = false
role_time = 0

[guidebook]
show_editor_species_button = false

[hub]
tags = "lang:ru,rp:low,region:eu_e"

[ic]
flavor_text = true

[infolinks]
bug_report = "https://discord.gg/dKng7WJZyn"
discord = "https://discord.gg/dKng7WJZyn"
github = "https://github.com/ttmc14/ttmc14"
patreon = "https://boosty.to/tornado_tech"
wiki = "https://wiki.rouny-ss14.com"

[net]
tickrate = 25
bindto = "::,0.0.0.0"

[physics]
grid_splitting = false
maxlinvelocity = 72
target_minimum_tickrate = 140

[pointing]
cooldown_seconds = 0.4

[procgen]
preload = false

[replay]
auto_record = false
max_compressed_size = 4194304
max_uncompressed_size = 8388608
auto_record_temp_dir = "recording"
auto_record_name = "done/{year}_{month}_{day}-{hour}_{minute}-round_{round}.zip"

[server]
rules_file = "RMCOverview"
default_guide = "RMC14"

[shuttle]
arrivals_planet = false
arrivals = false
preload_grids = false
startup_time = 10
travel_time = 100
arrival_time = 10
cooldown = 120
mass_limit = -1
emergency = false
auto_call_time = 0

[status]
enabled = false

[tips]
dataset = "CM_Tips"
login_dataset = "CM_Tips"

[vote]
preset_enabled = false
restart_ghost_percentage = 75
